name: Build

on:
  push: 
    branches: [ develop ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main, develop ]

env:
  configuration: Release
  productNamespacePrefix: "RxSerialPort"

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      nbgv: ${{ steps.nbgv.outputs.SemVer2 }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: | 
          6.0.x
          7.0.x
          8.0.x

    - name: NBGV
      id: nbgv
      uses: dotnet/nbgv@master      
      with:
        setAllVars: true

    - name: Restore
      run: dotnet restore
      working-directory: .     

    - name: Build
      run: dotnet build -v:minimal -c:${{ env.configuration }} 
      working-directory: .

    - name: Pack
      run: dotnet pack --no-build -v:minimal -c:${{ env.configuration }}
      working-directory: .

    - name: Install Report Generator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Run Unit Tests
      run: dotnet test --no-build -c:${{ env.configuration }} -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput="./artifacts/coverage/coverage.xml" -p:Include="[${{ env.productNamespacePrefix}}*]*"
      working-directory: .

    #- name: Generate Coverage Report
    #  run: reportgenerator -reports:"coverage.xml" -targetdir:report-output
    #  working-directory: artifacts/coverage

    #- name: Upload Code Coverage
    #  uses: codecov/codecov-action@v1
    #  with:
    #    token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos, otherwise set api token in repository secrets
    #    directory: artifacts/coverage

    - name: Create NuGet Artifacts
      uses: actions/upload-artifact@master
      with:
        name: nuget
        path: '**/*.nupkg'

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name == 'main' && github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download NuGet Packages
      uses: actions/download-artifact@v4
      with:
        name: nuget    

    - name: Changelog
      uses: glennawatson/ChangeLog@v1
      id: changelog

    - name: Create Release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: ${{ needs.build.outputs.nbgv }}
          release_name: ${{ needs.build.outputs.nbgv }}
          body: |
            ${{ steps.changelog.outputs.commitLog }}

    - name: NuGet Push
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }} # Set nuget api token in repository secrets
        SOURCE_URL: https://api.nuget.org/v3/index.json
      run: |
        dotnet nuget push -s ${{ env.SOURCE_URL }} -k ${{ env.NUGET_AUTH_TOKEN }} **/*.nupkg
